# Generated by Django 4.1.6 on 2023-02-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bool', '0002_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
