# Generated by Django 4.1.6 on 2023-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bool', '0004_rename_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoginField', models.CharField(max_length=18)),
                ('PasswordField', models.CharField(max_length=20)),
                ('EmailField', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
