# Generated by Django 4.1.6 on 2023-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bool', '0006_rename_emailfield_people_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
