# Generated by Django 4.1.6 on 2023-02-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bool', '0014_alter_post_image_alter_profile_awatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
