# Generated by Django 4.1.6 on 2023-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bool', '0015_remove_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='bool.profile'),
        ),
    ]
