# Generated by Django 4.1.6 on 2023-02-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bool', '0018_remove_profile_comment_remove_post_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='saved',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='awatar',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bool.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(related_name='post_comments', to='bool.comments'),
        ),
    ]
