# Generated by Django 4.1.6 on 2023-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bool', '0019_rename_save_post_saved_rename_awatar_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ManyToManyField(related_name='post_comments', to='bool.post'),
        ),
    ]
